-- D41：scene.decision_strategy ENUM 加 ALL_HITS / FIRST_HIT
ALTER TABLE scene
  MODIFY COLUMN decision_strategy ENUM('HIGHEST_PRIORITY','ALL_HITS','FIRST_HIT')
    NOT NULL DEFAULT 'HIGHEST_PRIORITY';
