spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

engine:
  rule:
    fetch:
      datasources:
        - name: loadtest_ro
          url: ${METRIC_DATASOURCE_URL:${SPRING_DATASOURCE_URL}}
          username: ${METRIC_DATASOURCE_USERNAME:${SPRING_DATASOURCE_USERNAME}}
          password: ${METRIC_DATASOURCE_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}
